### ISSUE TITLE
Adding 'pushState' behavior (requesting feedback!)

### ISSUE THREAD

**Issue by toddmohney** [gust/feature-creature-client#3]
I've been thinking about Elm as a tool to build a single page app, how that relates to FRP concepts, and the resulting architecture.

A simple example of how we have this working is:
- a user interacts with the page in some way
- the state of the page needs to update in accordance with the `Signal` created by the user interaction
- the views are then updated as a reaction to the changed state

As we have it, the `Signal` is something like: `ProductSelected` or `ReloadFeaturesClicked`
What's currently missing is a corresponding URI associated with this new state.

It is my intuition that, in most cases, we want the `Signal` to, not describe the explicit interaction, but to update the URI. Updating the URI will, in turn, create a new `Signal` containing the new URI (a description of the current state) which then can be used to load new data, modify the DOM, etc.

A counter example to the flow above would be:
- a user interacts with the page in some way
- the URL is updated reflecting the state we wish the view to reflect
- the application reacts to the change in URL
- the views are updated according to the new (now addressable!) state

Using this pattern, I believe we benefit by
1. Creating a highly navigable and reproducible website by codifying our view states as URIs.
2. Creating a unified manner in which view states are to be rendered.*
- to explain what I mean here...
  If we choose to not place the URI as a first-class citizen and treat it as an artifact of a user interaction (any `Signal`, really), then we will have a difficult time recreating view state from a user navigating directly to a URI (in other words, not creating the sequence of `Signals` which built that URI initially)
  If we always render views based on a URI change `Signal` we achieve a single canonical path to recreating the correct state. Meaning, we no longer care what events got us into this state, we just need to know the state itself.

I found a library that can help us build up this idea [elm-history](https://github.com/TheSeamau5/elm-history)

**Comment by noahzgordon** [comment]
I like the idea. We did something similar for the Redux application we're building on Zephyr. 

Elm and Redux are similar philosphically in that they believe that the view should always be the expression of a single, immutable state object. In Redux this is the 'store', and in Elm the 'model'. Elm sticks a bit more strictly to the FRP idea by reading state from a continuous stream of Signals.

For the Redux app we interpreted the URI similarly, as an expression of the state tree. On every state update, the URI is updated alongside the view. On initialization, state is unpacked from the URI.

This is a bit different from what you've proposed. The idea of the URI being the single source of truth for client state is interesting. With the Elm architecture, all we would really need is a function that can take a URI and construct a top-level model from it. Then every link on the page is actually just that -- a link which triggers a signal containing the given href.

Not sure how we would handle URIs which correspond to side effects (anything that needs to modify/destroy server data). I suppose these would be Effects triggered by the URI change? So a URI corresponds not just to a view model, but to a view model + other effects.

**Comment by pdswan** [comment]
haha. woops. that button does _not_ say cancel!

having trouble formalizing my thoughts on this; i agree that considering how the web application URL maps to a view of the application is important and it makes sense to do that up front.

i'm not sure i thoroughly understand what you're advocating, but i've got hesitations about encoding data in the URI and expressing all actions through URI changes. i _think_ it's because it's overloading what the URI is _for_ and coupling things more closely than i'm comfortable with.

it would probably be helpful to see some code; i'll keep thinking on it.
